Repository ProjectPythia/projectpythia.github.io, pull requests merged in 2021-11, with the labels that each got.

#180 Add photos to Team page
  portal/index.md
  portal/people.md
Labels: infrastructure, hackathon

#182 Add Chris Cardinale to team list
  portal/index.md
Labels: content

#151 Add Twitter button to Portal Navbar
  sphinx_pythia_theme/header.html
Labels: infrastructure

#178 Multiple Gallery Filters
  portal/_extensions/yaml_gallery_generator.py
  portal/_static/custom.js
  portal/gallery/.keep
Labels: infrastructure

#187 Adding Foundations Content to Resource Gallery
  portal/_static/thumbnails/ProjectPythia_Blue.png
  portal/gallery.yaml
Labels: content
